### ISSUE TITLE
Auto checkin fails if reservation has been changed by phone

### ISSUE THREAD

**Issue by scarolan** [springyleap/southwest-autocheckin#3]
It seems like once an employee makes changes to an itinerary manually, that those changes are no longer reflected in the webui.  I had a flight recently that I had to change, but when I put the confirmation number into springyleap.com it returns the old itinerary.

**Comment by josecomboni** [comment]
You need to go to your fights reminders (click the link at the bottom of the registration page)and delete the existing flight  you want to change. Then, load the modified flight. This is indeed a little more complex than desired, and I'm open to suggestions.

**Comment by scarolan** [comment]
How about a simple note on the page:

"Note:  If you change your reservation, be sure to delete and re-add it to our system to ensure that auto check-in will function correctly."
